In [1]:
!pip install transformers
!pip install sentencepiece
!pip install torch

In [2]:
from transformers import AutoTokenizer, AutoModel

model_name = "klue/roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

C:\Users\liber\anaconda3\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\liber\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


Some weights of RobertaModel were not initialized from the model checkpoint at klue/roberta-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [152]:
dir(model)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_auto_class',
 '_backward_compatibility_gradient_checkpointing',
 '_backward_hooks',
 '_buffers',
 '_call_impl',
 '_convert_head_mask_to_5d',
 '_create_repo',
 '_expand_inputs_for_generation',
 '_extract_past_from_model_output',
 '_forward_hooks',
 '_forward_pre_hooks',
 '_from_config',
 '_get_backward_hooks',
 '_get_decoder_start_token_id',
 '_get_files_timestamps',
 '_get_generation_mode',
 '_get_logits_processor',
 '_get_logits_warper',
 '_get_name',
 '_get_resized_embeddings',
 '_get_resized_lm_head',
 '_get_stopping_criter

In [4]:
!pip install torch

In [6]:
import torch

In [91]:
document = "한국의 수도는 서울이며, 대표적인 관광지로는 경복궁, 덕수궁, 남산 타워 등이 있습니다. 한국은 한반도에 위치하며, 서울은 대한민국의 수도입니다."

# 문서를 토큰화하고 KLUE RoBERTa 모델에 입력할 형식으로 변환
tokens = tokenizer.tokenize(tokenizer.decode(tokenizer.encode(document)))
input_ids = tokenizer.convert_tokens_to_ids(tokens)
input_ids = torch.tensor(input_ids).unsqueeze(0)  # 배치 차원 추가

# KLUE RoBERTa 모델을 사용하여 키워드 추출
with torch.no_grad():
    outputs = model(input_ids)

# 출력을 키워드로 변환
# keyword_indices = torch.topk(outputs.logits[0], k=5).indices  # 상위 5개 키워드 추출
# keywords = [tokenizer.decode(index) for index in keyword_indices]

# print("추출된 키워드:", keywords)


In [101]:
len(tokens)

42

In [102]:
outputs.last_hidden_state[0]

tensor([[ 0.0919, -0.6115, -0.1571,  ..., -0.1492, -0.1905,  0.1406],
        [-0.6565, -0.2256, -0.2437,  ...,  0.0889, -0.1331,  0.0465],
        [-0.4368, -0.5798,  0.2262,  ..., -0.4706, -0.2786, -0.2569],
        ...,
        [-0.2876, -0.5503, -0.1821,  ..., -0.7832, -0.0448, -0.2131],
        [-0.2211, -0.1324,  0.1354,  ..., -0.2847, -0.1898, -0.2840],
        [ 0.0912, -0.6113, -0.1571,  ..., -0.1497, -0.1902,  0.1407]])

In [39]:
from kiwipiepy import Kiwi
kiwi = Kiwi()

In [40]:
result = kiwi.analyze(document)
result

[([Token(form='한국', tag='NNP', start=0, len=2),
   Token(form='의', tag='JKG', start=2, len=1),
   Token(form='수도', tag='NNG', start=4, len=2),
   Token(form='는', tag='JX', start=6, len=1),
   Token(form='서울', tag='NNP', start=8, len=2),
   Token(form='이', tag='VCP', start=10, len=1),
   Token(form='며', tag='EC', start=11, len=1),
   Token(form=',', tag='SP', start=12, len=1),
   Token(form='대표', tag='NNG', start=14, len=2),
   Token(form='적', tag='XSN', start=16, len=1),
   Token(form='이', tag='VCP', start=17, len=1),
   Token(form='ᆫ', tag='ETM', start=17, len=1),
   Token(form='관광지', tag='NNG', start=19, len=3),
   Token(form='로', tag='JKB', start=22, len=1),
   Token(form='는', tag='JX', start=23, len=1),
   Token(form='경복궁', tag='NNP', start=25, len=3),
   Token(form=',', tag='SP', start=28, len=1),
   Token(form='덕수궁', tag='NNP', start=30, len=3),
   Token(form=',', tag='SP', start=33, len=1),
   Token(form='남산', tag='NNP', start=35, len=2),
   Token(form='타워', tag='NNG', start=38,

In [107]:
tokens
hidden_states[0]

tensor([[ 0.0919, -0.6115, -0.1571,  ..., -0.1492, -0.1905,  0.1406],
        [-0.6565, -0.2256, -0.2437,  ...,  0.0889, -0.1331,  0.0465],
        [-0.4368, -0.5798,  0.2262,  ..., -0.4706, -0.2786, -0.2569],
        ...,
        [-0.2876, -0.5503, -0.1821,  ..., -0.7832, -0.0448, -0.2131],
        [-0.2211, -0.1324,  0.1354,  ..., -0.2847, -0.1898, -0.2840],
        [ 0.0912, -0.6113, -0.1571,  ..., -0.1497, -0.1902,  0.1407]])

In [153]:
document = "한국의 수도는 서울이며, 대표적인 관광지로는 경복궁, 덕수궁, 남산 타워 등이 있습니다. 한국은 한반도에 위치하며, 서울은 대한민국의 수도입니다."

# 문서를 토큰화하고 KLUE RoBERTa 모델에 입력할 형식으로 변환
# tokens = tokenizer.tokenize(tokenizer.decode(tokenizer.encode(document)))
tokens = tokenizer.tokenize(tokenizer.decode(tokenizer.encode(document)))
# tokens = tokenizer.tokenize(document)
input_ids = tokenizer.convert_tokens_to_ids(tokens)
input_ids = torch.tensor(input_ids).unsqueeze(0)  # 배치 차원 추가

# KLUE RoBERTa 모델을 사용하여 키워드 추출
with torch.no_grad():
    outputs = model(input_ids)

# 출력에서 특성 벡터를 추출
document_embedding = outputs.last_hidden_state.mean(dim=1)
# hidden_states = outputs.last_hidden_state  # 또는 다른 특성 벡터를 선택할 수 있음

# 특성 벡터를 이용하여 키워드 추출
# keyword_indices = hidden_states.sum(dim=1).argsort(descending=True)[:5]  # 예: 특성 벡터의 합을 계산하고 상위 5개 키워드 추출
# keyword_indices = hidden_states[0].sum(dim=1).argsort(descending=True)[:5]

# 추출된 키워드를 토큰으로 디코딩
# keywords = [tokenizer.decode(index) for index in keyword_indices]

# print("추출된 키워드:", keywords)


In [159]:
document_embedding = outputs.last_hidden_state.mean(dim=1)
document_embedding

tensor([[-2.7157e-01, -3.3834e-01, -7.7369e-02,  8.1869e-02, -9.9433e-02,
         -9.7849e-02, -2.9301e-01, -8.0296e-02, -1.1782e-01, -1.0657e-01,
         -3.1969e-01, -2.9930e-02, -1.4570e-01,  7.7773e-02,  2.4389e-01,
          1.1578e-01, -5.1697e-02, -2.9688e-01, -1.0575e-01, -1.0342e+00,
         -2.5812e-01, -1.3786e-01,  2.5015e-01,  1.3543e-02, -7.4338e-02,
         -6.4721e-03, -8.4474e-03, -7.8043e-02,  1.4895e-02,  4.5210e-02,
         -3.6226e-01, -2.1439e-01,  1.5156e-01,  4.3437e-01,  1.2388e+00,
          8.3585e-02,  5.8983e-04, -9.5695e-02,  2.2734e-01, -1.1294e-01,
         -8.9996e-02, -2.7805e-01,  4.3254e-01, -4.5504e-02,  4.2163e-01,
         -2.5948e-01,  3.3295e-01,  2.4800e-01,  2.9312e-01, -1.6788e-01,
          3.1843e-01, -2.3574e-01,  2.4051e-01, -8.1318e-01, -1.4138e-01,
         -7.1206e-03, -9.1241e-03,  2.7616e-01, -1.0786e-01, -1.4901e-01,
          2.7782e-01, -4.7767e-02,  1.9005e-01, -1.7243e-01, -2.7055e-01,
          1.8737e-02, -1.4951e-01, -1.

In [163]:
outputs.last_hidden_state.shape

torch.Size([1, 42, 768])

In [164]:
model.embeddings.word_embeddings

Embedding(32000, 768, padding_idx=1)

In [162]:
import numpy as np

# 문서 임베딩과 각 단어 임베딩 간의 코사인 유사도 계산
word_embeddings = outputs.last_hidden_state[0]  # 각 단어의 임베딩 벡터 (예: shape = [단어 개수, 임베딩 차원])
document_embedding = outputs.last_hidden_state.mean(dim=1)  # 문서의 임베딩 벡터 (예: shape = [1, 임베딩 차원])

# 내적 계산
dot_product = np.dot(word_embeddings, document_embedding.T)  # 각 단어 임베딩과 문서 임베딩 간의 내적

# 각 벡터의 크기(norm) 계산
word_embedding_norms = np.linalg.norm(word_embeddings, axis=1)  # 각 단어 임베딩의 크기
document_embedding_norm = np.linalg.norm(document_embedding)  # 문서 임베딩의 크기

# 코사인 유사도 계산
cosine_similarities = dot_product / (word_embedding_norms * document_embedding_norm)

# 코사인 유사도를 기준으로 가장 유사한 단어 선택
most_similar_word_index = np.argmax(cosine_similarities)
most_similar_word_index
# most_similar_word = tokens[most_similar_word_index]  # 단어 인덱스를 단어로 변환


974

In [154]:
import numpy as np

# 문서 임베딩과 각 단어 임베딩 간의 코사인 유사도 계산
word_embeddings = outputs.last_hidden_state[0]  # 모든 단어의 임베딩
cosine_similarities = np.dot(word_embeddings, document_embedding) / (np.linalg.norm(word_embeddings, axis=1) * np.linalg.norm(document_embedding))

# 가장 유사도가 높은 단어 선택
representative_word_index = np.argmax(cosine_similarities)
representative_word = tokens[representative_word_index]

print("대표 단어:", representative_word)


ValueError: shapes (42,768) and (1,768) not aligned: 768 (dim 1) != 1 (dim 0)

In [135]:
tokens = tokenizer.tokenize(tokenizer.decode(tokenizer.encode(document)))
cnt = 1
for t in tokens:
    print(t, cnt)
    cnt +=1

[CLS] 1
한국 2
##의 3
수도 4
##는 5
서울 6
##이 7
##며 8
, 9
대표 10
##적인 11
관광지 12
##로 13
##는 14
경복궁 15
, 16
덕수궁 17
, 18
남산 19
타워 20
등 21
##이 22
있 23
##습 24
##니다 25
. 26
한국 27
##은 28
한반도 29
##에 30
위치 31
##하 32
##며 33
, 34
서울 35
##은 36
대한민국 37
##의 38
수도 39
##입니다 40
. 41
[SEP] 42


In [141]:
tokenizer.encode(document)

[0,
 3629,
 2079,
 4438,
 2259,
 3671,
 2052,
 2307,
 16,
 3661,
 31221,
 9417,
 2200,
 2259,
 17587,
 16,
 26875,
 16,
 12103,
 8203,
 886,
 2052,
 1513,
 2219,
 3606,
 18,
 3629,
 2073,
 5409,
 2170,
 4318,
 2205,
 2307,
 16,
 3671,
 2073,
 4892,
 2079,
 4438,
 12190,
 18,
 2]

In [134]:
tokens = tokenizer.tokenize(document)
cnt = 1
for t in tokens:
    print(t, cnt)
    cnt +=1

한국 1
##의 2
수도 3
##는 4
서울 5
##이 6
##며 7
, 8
대표 9
##적인 10
관광지 11
##로 12
##는 13
경복궁 14
, 15
덕수궁 16
, 17
남산 18
타워 19
등 20
##이 21
있 22
##습 23
##니다 24
. 25
한국 26
##은 27
한반도 28
##에 29
위치 30
##하 31
##며 32
, 33
서울 34
##은 35
대한민국 36
##의 37
수도 38
##입니다 39
. 40


In [120]:
len(tokenizer.encode(document))

42

In [122]:
len(hidden_states[0])

42

In [127]:
hidden_states[0].sum(dim=1).argsort(descending=True)[:5]

tensor([32, 17, 29, 15, 31])

In [130]:
len(hidden_states[0].sum(dim=1).argsort(descending=True)[:5])

5

In [116]:
keyword_indices = hidden_states[0].argsort(descending=True)[:5]
keyword_indices[0]

tensor([345, 293,  34,  69, 573,  80,  94, 426, 280, 498, 404, 628, 349, 135,
        111, 186, 331, 141, 257, 643, 689, 457, 441, 622,  44, 659, 691, 388,
        685, 248, 189,  50, 557, 335, 300, 367, 510, 216, 419, 687, 660, 338,
         98, 301, 546, 322, 519, 670,  82, 411,  61, 692, 382, 483, 102, 621,
         63, 467, 319,  64, 403, 324, 488, 406, 545, 455, 585, 610, 290, 493,
         95, 168, 333, 530, 682, 470, 431, 592,  52,  22,  42, 121, 619, 214,
        328, 506, 623, 547, 271, 603, 412,  86, 287, 387,  23,  26, 184, 400,
        698, 440, 368, 396, 705, 109, 616, 173, 204, 554, 100, 503, 541, 681,
        724, 294, 466, 542, 265, 538, 296, 149, 219, 718, 572, 674, 508, 604,
        543, 492, 220,  60, 145,  55, 143, 342, 166, 520, 273, 744, 144, 125,
        657, 627, 767, 719, 252, 661, 446, 601, 325, 237, 393,  13, 501, 588,
          4, 747, 752, 559, 560, 617, 611, 608, 267, 258,  76,  43, 185, 423,
        703, 224, 593, 631, 721, 540, 392, 490, 529, 306, 671, 5

In [136]:
result = kiwi.tokenize(document)
result

[Token(form='한국', tag='NNP', start=0, len=2),
 Token(form='의', tag='JKG', start=2, len=1),
 Token(form='수도', tag='NNG', start=4, len=2),
 Token(form='는', tag='JX', start=6, len=1),
 Token(form='서울', tag='NNP', start=8, len=2),
 Token(form='이', tag='VCP', start=10, len=1),
 Token(form='며', tag='EC', start=11, len=1),
 Token(form=',', tag='SP', start=12, len=1),
 Token(form='대표', tag='NNG', start=14, len=2),
 Token(form='적', tag='XSN', start=16, len=1),
 Token(form='이', tag='VCP', start=17, len=1),
 Token(form='ᆫ', tag='ETM', start=17, len=1),
 Token(form='관광지', tag='NNG', start=19, len=3),
 Token(form='로', tag='JKB', start=22, len=1),
 Token(form='는', tag='JX', start=23, len=1),
 Token(form='경복궁', tag='NNP', start=25, len=3),
 Token(form=',', tag='SP', start=28, len=1),
 Token(form='덕수궁', tag='NNP', start=30, len=3),
 Token(form=',', tag='SP', start=33, len=1),
 Token(form='남산', tag='NNP', start=35, len=2),
 Token(form='타워', tag='NNG', start=38, len=2),
 Token(form='등', tag='NNB', start

In [65]:
dir(outputs)

['__annotations__',
 '__class__',
 '__contains__',
 '__dataclass_fields__',
 '__dataclass_params__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__post_init__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'attentions',
 'clear',
 'copy',
 'cross_attentions',
 'fromkeys',
 'get',
 'hidden_states',
 'items',
 'keys',
 'last_hidden_state',
 'move_to_end',
 'past_key_values',
 'pooler_output',
 'pop',
 'popitem',
 'setdefault',
 'to_tuple',
 'update',
 'values']

In [69]:
outputs.last_hidden_state

tensor([[[ 0.0919, -0.6115, -0.1571,  ..., -0.1492, -0.1905,  0.1406],
         [-0.6565, -0.2256, -0.2437,  ...,  0.0889, -0.1331,  0.0465],
         [-0.4368, -0.5798,  0.2262,  ..., -0.4706, -0.2786, -0.2569],
         ...,
         [-0.2876, -0.5503, -0.1821,  ..., -0.7832, -0.0448, -0.2131],
         [-0.2211, -0.1324,  0.1354,  ..., -0.2847, -0.1898, -0.2840],
         [ 0.0912, -0.6113, -0.1571,  ..., -0.1497, -0.1902,  0.1407]]])

In [151]:
ids = tokenizer.convert_tokens_to_ids(tokens)
ids
#tokenizer.decode(tokenizer.prepare_for_model(ids).input_ids)

[0,
 3629,
 2079,
 4438,
 2259,
 3671,
 2052,
 2307,
 16,
 3661,
 31221,
 9417,
 2200,
 2259,
 17587,
 16,
 26875,
 16,
 12103,
 8203,
 886,
 2052,
 1513,
 2219,
 3606,
 18,
 3629,
 2073,
 5409,
 2170,
 4318,
 2205,
 2307,
 16,
 3671,
 2073,
 4892,
 2079,
 4438,
 12190,
 18,
 2]

In [ ]:
#keybert 시작

In [2]:
!pip install keybert

  Using cached torch-2.0.1-cp38-cp38-win_amd64.whl (172.4 MB)
  Attempting uninstall: torch
    Found existing installation: torch 2.0.0
    Uninstalling torch-2.0.0:
      Successfully uninstalled torch-2.0.0


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformer-smaller-training-vocab 0.3.2 requires torch!=2.0.1,<3.0.0,>=1.8.0, but you have torch 2.0.1 which is incompatible.


In [3]:
#Sentence Transformers 
from sentence_transformers import SentenceTransformer
#modelname = 'all-mpnet-base-v2'
modelname = 'distiluse-base-multilingual-cased-v1'
model = SentenceTransformer(modelname)

C:\Users\liber\anaconda3\envs\fiveCart\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [167]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer(modelname)

query_embedding = model.encode('How big is London')
passage_embedding = model.encode(['London has 9,787,426 inhabitants at the 2011 census',
                                  'London is known for its finacial district'])

print("Similarity:", util.dot_score(query_embedding, passage_embedding))

Similarity: tensor([[0.6286, 0.4823]])


In [4]:
from keybert import KeyBERT
from sentence_transformers import SentenceTransformer

In [5]:
modelname = 'distiluse-base-multilingual-cased-v1'
model = SentenceTransformer(modelname)
kw_model = KeyBERT(model)

In [9]:
document = """
            한국의 수도는 서울이며, 대표적인 관광지로는 경복궁, 덕수궁, 남산 타워 등이 있습니다.
            한국은 한반도에 위치하며, 서울은 대한민국의 수도입니다.
            """

In [7]:
doc = """
         Supervised learning is the machine learning task of learning a function that
         maps an input to an output based on example input-output pairs. It infers a
         function from labeled training data consisting of a set of training examples.
         In supervised learning, each example is a pair consisting of an input object
         (typically a vector) and a desired output value (also called the supervisory signal).
         A supervised learning algorithm analyzes the training data and produces an inferred function,
         which can be used for mapping new examples. An optimal scenario will allow for the
         algorithm to correctly determine the class labels for unseen instances. This requires
         the learning algorithm to generalize from the training data to unseen situations in a
         'reasonable' way (see inductive bias).
      """
keywords = kw_model.extract_keywords(document)

In [8]:
keywords

[('서울이며', 0.4386),
 ('서울은', 0.4364),
 ('한국은', 0.3665),
 ('한반도에', 0.3538),
 ('한국의', 0.336)]

In [9]:
kw_model.extract_keywords(document, keyphrase_ngram_range=(1, 2), stop_words=None)

[('서울은 대한민국의', 0.5274),
 ('수도는 서울이며', 0.5263),
 ('서울이며 대표적인', 0.5125),
 ('위치하며 서울은', 0.5115),
 ('한국은 한반도에', 0.4796)]

In [ ]:
#flair 적용 시작

In [5]:
!pip install --user flair
import flair

In [6]:
from keybert import KeyBERT
from flair.embeddings import TransformerDocumentEmbeddings

roberta = TransformerDocumentEmbeddings('roberta-base')
kw_model = KeyBERT(model=roberta)

In [7]:
from keybert import KeyBERT
from flair.embeddings import TransformerDocumentEmbeddings

roberta = TransformerDocumentEmbeddings('klue/roberta-base')
kw_model = KeyBERT(model=roberta)

In [10]:
kw_model.extract_keywords(document, keyphrase_ngram_range=(1, 2), stop_words=None)

[('수도는 서울이며', 0.9882),
 ('관광지로는 경복궁', 0.9868),
 ('대한민국의 수도입니다', 0.9865),
 ('대표적인 관광지로는', 0.9864),
 ('서울은 대한민국의', 0.9863)]

In [16]:
kw_model.extract_keywords(document, keyphrase_ngram_range=(1, 1), stop_words=None)

[('서울이며', 0.9861),
 ('관광지로는', 0.9849),
 ('수도입니다', 0.9847),
 ('있습니다', 0.9847),
 ('한국의', 0.9839)]